name: Deploy on server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
          fetch-depth: 1

      - name: Setup .env file and GCP credentials
        env:
          PROD_ENV: ${{ secrets.PROD_ENV }}
          GCP_CREDS: ${{ secrets.GCP_CREDS }}
        run: |
          echo "$PROD_ENV" | base64 -d > .env
          echo "$GCP_CREDS" | base64 -d > gcpCreds.json

      - name: Setup key
        env:
          ECD_KEY: ${{ secrets.ECD_KEY }}
        run: |
          echo "$ECD_KEY" | base64 -d > $HOME/ecd
          chmod 400 $HOME/ecd

      - name: Push the build to server
        run: rsync -avz --delete --exclude 'node_modules' --exclude '.git*' -e "ssh -i $HOME/ecd -o StrictHostKeyChecking=no" ./ ops@speech.prem.codes:/var/www/speech-api/

      - name: install dependencies on remote server
        run: ssh -i $HOME/ecd -o StrictHostKeyChecking=no ops@speech.prem.codes 'cd /var/www/speech-api/ && yarn install --prod && pm2 restart speech-api'